version: '3'

services:
  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: student-portal-mongo
    ports:
      - "5003:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - app-network

  # Backend service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: student-portal-server
    restart: unless-stopped
    ports:
      - "${SERVER_PORT}:5003"
    env_file: .env
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - app-network

  # Frontend service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: student-portal-client
    restart: unless-stopped
    ports:
      - "${CLIENT_PORT}:3000"
    env_file: .env
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local

